const express = require('express');
const { DatabaseSync } = require('node:sqlite');
const { randomBytes, randomUUID } = require('node:crypto');
const bcrypt = require('bcryptjs');
const QRCode = require('qrcode');
const multer = require('multer');
const fs = require('node:fs');
const path = require('node:path');
const app = express();
const dataDir = process.env.DATA_DIR || path.join(__dirname, 'data');
fs.mkdirSync(dataDir, { recursive: true });
const db = new DatabaseSync(path.join(dataDir, 'smartclass.sqlite'));
db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS store (id INTEGER PRIMARY KEY, value TEXT NOT NULL)');
const read = db.prepare('SELECT value FROM store WHERE id=1');
const write = db.prepare('INSERT INTO store VALUES (1, ?) ON CONFLICT(id) DO UPDATE SET value=excluded.value');
const id = () => randomUUID();
const now = () => new Date().toISOString();
const publicUser = ({password, ...user}) => user;
const seed = () => {
  const password = bcrypt.hashSync('password123', 10);
  const users = [{id:'teacher',name:'Yasin Sazid',email:'teacher@smartclass.local',role:'teacher',password,bio:'Lecturer · Department of Computer Science',phone:''},{id:'student',name:'Afridi Hasan',email:'student@smartclass.local',role:'student',password,bio:'Computer Science student',phone:''},{id:'guardian',name:'Samira Hasan',email:'guardian@smartclass.local',role:'guardian',password,bio:'',phone:''}];
  const classes = [['c1','Software Engineering','CSE 412','05','A-402','#8b7cf8','Design thoughtful software, from requirements to release.'],['c2','Database Management','CSE 302','02','B-305','#55c4b4','Explore the data behind every great application.'],['c3','Computer Networks','CSE 405','01','A-601','#efb365','Connect the dots. Understand how the world communicates.']].map(([id,name,subject,section,room,color,description],i)=>({id,name,subject,section,room,color,description,teacherId:'teacher',code:['SC41205','DB30202','CN40501'][i],students:['student'],limit:40,archivedAt:null,createdAt:now()}));
  const assignments = [{id:'a1',classId:'c1',title:'Software requirements specification',description:'Prepare an SRS for your semester project. Include stakeholder needs, functional requirements, and a use case diagram.',points:100,due:new Date(Date.now()+86400000*2).toISOString(),createdAt:now()},{id:'a2',classId:'c2',title:'Design a relational database',description:'Create an ER diagram and normalize your schema to third normal form.',points:50,due:new Date(Date.now()+86400000*4).toISOString(),createdAt:now()},{id:'a3',classId:'c3',title:'Explore the OSI model',description:'Explain each layer with an everyday example.',points:20,due:new Date(Date.now()-86400000).toISOString(),createdAt:now()}];
  return {users,classes,assignments,submissions:[{id:'s1',assignmentId:'a3',studentId:'student',text:'My explanation of the seven OSI layers.',createdAt:new Date(Date.now()-172800000).toISOString(),grade:17,feedback:'Good examples. Expand your explanation of the transport layer.',late:false}],posts:[{id:'p1',classId:'c1',authorId:'teacher',text:'Welcome to the new semester! Our project journey starts here. Review the course outline and bring your ideas to our next class.',createdAt:now()}],materials:[],quizzes:[{id:'q1',classId:'c1',title:'Software process fundamentals',minutes:10,status:'live',questions:[{text:'Which model uses short, iterative development cycles?',options:['Waterfall','Agile','Big bang','V-model'],answer:1},{text:'What does SRS stand for?',options:['System Runtime Service','Software Requirements Specification','Software Release Standard','Secure Remote Server'],answer:1}],createdAt:now()}],attempts:[],polls:[],attendanceSessions:[],attendance:[],links:[],messages:[],events:[],notifications:[{id:'n1',userId:'student',text:'Welcome to SmartClass. Your learning journey starts here.',read:false,createdAt:now()}],files:[],sessions:[],offline:[]};
};
let state = read.get();
state = state ? JSON.parse(state.value) : seed();
const save = () => write.run(JSON.stringify(state));
save();
function fail(message, status=400){ const e=new Error(message); e.status=status; throw e; }
function str(v,label,max=5000){ if(typeof v!=='string'||!v.trim()||v.length>max) fail(`${label} is required (maximum ${max} characters).`); return v.trim(); }
function num(v,min,max,label){ const n=Number(v); if(!Number.isFinite(n)||n<min||n>max) fail(`${label} must be between ${min} and ${max}.`); return n; }
function date(v){if(!v||!Number.isFinite(Date.parse(v))) fail('Choose a valid date.'); return new Date(v).toISOString();}
function role(u,r){if(u.role!==r) fail('This action is not available for your role.',403);}
function classroom(u,cid,owner=false,active=true){const c=state.classes.find(c=>c.id===cid);if(!c) fail('Class not found.',404);if(owner?c.teacherId!==u.id:!(c.teacherId===u.id||c.students.includes(u.id)))fail('You do not have access to this class.',403);if(active&&c.archivedAt)fail('Restore this class before making changes.');return c;}
function notify(userId,text){state.notifications.unshift({id:id(),userId,text,createdAt:now(),read:false});}
function members(c,text){c.students.forEach(uid=>notify(uid,text));}
function attachment(u,fileId){if(!fileId)return null;const f=state.files.find(x=>x.id===fileId&&x.ownerId===u.id);if(!f)fail('File not found.',404);return f.id;}
function studentIds(u){if(u.role==='student')return[u.id];if(u.role==='guardian')return state.links.filter(l=>l.guardianId===u.id&&l.status==='approved').map(l=>l.studentId);return [...new Set(state.classes.filter(c=>c.teacherId===u.id).flatMap(c=>c.students))];}
function metrics(uid,cids){const assignments=state.assignments.filter(a=>cids.includes(a.classId));const subs=state.submissions.filter(s=>s.studentId===uid&&assignments.some(a=>a.id===s.assignmentId));const graded=subs.filter(s=>s.grade!==null&&s.grade!==undefined);const sessions=state.attendanceSessions.filter(s=>cids.includes(s.classId));const days=[...new Set(sessions.map(s=>s.classId+'|'+s.date))];const att=state.attendance.filter(a=>a.studentId===uid&&cids.includes(a.classId));const attempts=state.attempts.filter(a=>a.studentId===uid&&a.submittedAt&&state.quizzes.some(q=>q.id===a.quizId&&cids.includes(q.classId)));return {studentId:uid,name:state.users.find(u=>u.id===uid)?.name,average:graded.length?Math.round(graded.reduce((n,s)=>n+s.grade/state.assignments.find(a=>a.id===s.assignmentId).points*100,0)/graded.length):null,attendance:days.length?Math.round(att.filter(a=>['present','late','excused'].includes(a.status)).length/days.length*100):null,quiz:attempts.length?Math.round(attempts.reduce((n,a)=>n+a.score/a.total*100,0)/attempts.length):null,submission:assignments.length?Math.round(subs.length/assignments.length*100):null};}
app.disable('x-powered-by');
app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"});if(req.path.startsWith('/api'))res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin&&req.headers.origin!==`${req.protocol}://${req.get('host')}`)return res.status(403).json({error:'Cross-origin requests are not allowed.'});next();});
app.use(express.json({limit:'1mb'}));
const limits=new Map();
app.use('/api/auth',(req,res,next)=>{const key=req.ip;const value=limits.get(key)||{n:0,end:Date.now()+60000};if(Date.now()>value.end){value.n=0;value.end=Date.now()+60000;}value.n++;limits.set(key,value);if(value.n>40)return res.status(429).json({error:'Too many attempts. Please wait one minute.'});next();});
function sessionCookie(res,token){res.cookie('smartclass',token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE==='1',maxAge:86400000,path:'/'});}
app.post('/api/auth/:action',(req,res)=>{const b=req.body;let u;if(req.params.action==='register'){const name=str(b.name,'Name',100),email=str(b.email,'Email',160).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('Enter a valid email.');if(!['teacher','student','guardian'].includes(b.role))fail('Choose a valid role.');if(state.users.some(u=>u.email===email))fail('An account already uses this email.');const password=str(b.password,'Password',72);if(password.length<8)fail('Use at least 8 characters for your password.');u={id:id(),name,email,role:b.role,password:bcrypt.hashSync(password,10),bio:'',phone:''};state.users.push(u);}else if(req.params.action==='login'){u=state.users.find(u=>u.email===String(b.email).trim().toLowerCase());if(!u||!bcrypt.compareSync(String(b.password||''),u.password))fail('Email or password is incorrect.',401);}else fail('Not found.',404);const token=randomBytes(32).toString('hex');state.sessions=state.sessions.filter(s=>s.expires>Date.now());state.sessions.push({token,userId:u.id,expires:Date.now()+86400000,history:[]});sessionCookie(res,token);save();res.json(publicUser(u));});
app.use('/api',(req,res,next)=>{const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('smartclass='))?.slice(11);const session=state.sessions.find(s=>s.token===token&&s.expires>Date.now());if(!session)return res.status(401).json({error:'Please sign in to continue.'});req.session=session;req.user=state.users.find(u=>u.id===session.userId);next();});
app.post('/api/logout',(req,res)=>{state.sessions=state.sessions.filter(s=>s!==req.session);save();res.clearCookie('smartclass');res.json({ok:true});});
app.get('/api/state',(req,res)=>{const u=req.user,ids=studentIds(u);const classes=state.classes.filter(c=>u.role==='teacher'?c.teacherId===u.id:u.role==='student'?c.students.includes(u.id):c.students.some(s=>ids.includes(s)));const cids=classes.map(c=>c.id);const assignments=state.assignments.filter(a=>cids.includes(a.classId));const quizzes=state.quizzes.filter(q=>cids.includes(q.classId)).filter(q=>u.role==='teacher'||q.status!=='draft').map(q=>({...q,questions:q.questions.map(({answer,...rest})=>u.role==='teacher'?{...rest,answer}:rest)}));const contacts=state.users.filter(x=>x.id!==u.id&&(classes.some(c=>[c.teacherId,...c.students].includes(x.id))||state.links.some(l=>[l.studentId,l.guardianId].includes(u.id)&&[l.studentId,l.guardianId].includes(x.id))));res.json({user:publicUser(u),classes,assignments,submissions:state.submissions.filter(s=>assignments.some(a=>a.id===s.assignmentId)&&(u.role==='teacher'||ids.includes(s.studentId))),posts:state.posts.filter(p=>cids.includes(p.classId)),materials:state.materials.filter(m=>cids.includes(m.classId)),quizzes,attempts:state.attempts.filter(a=>quizzes.some(q=>q.id===a.quizId)&&(u.role==='teacher'||ids.includes(a.studentId))),polls:state.polls.filter(p=>cids.includes(p.classId)).map(p=>({...p,votes:undefined,counts:p.options.map((_,i)=>p.votes.filter(v=>v.option===i).length),myVote:p.votes.find(v=>v.userId===u.id)?.option})),attendanceSessions:state.attendanceSessions.filter(s=>cids.includes(s.classId)).map(({token,...s})=>s),attendance:state.attendance.filter(a=>cids.includes(a.classId)&&(u.role==='teacher'||ids.includes(a.studentId))),links:state.links.filter(l=>l.guardianId===u.id||l.studentId===u.id),contacts:contacts.map(publicUser),messages:state.messages.filter(m=>m.classId?cids.includes(m.classId)&&u.role!=='guardian':m.from===u.id||m.to===u.id),events:state.events.filter(e=>cids.includes(e.classId)),notifications:state.notifications.filter(n=>n.userId===u.id),analytics:ids.map(uid=>metrics(uid,cids.filter(cid=>classes.find(c=>c.id===cid).students.includes(uid)))),aiConfigured:!!(process.env.OPENROUTER_API_KEY&&process.env.OPENROUTER_MODEL)});});
app.post('/api/profile',(req,res)=>{req.user.name=str(req.body.name,'Name',100);req.user.bio=String(req.body.bio||'').slice(0,500);req.user.phone=String(req.body.phone||'').slice(0,30);save();res.json({ok:true});});
app.post('/api/classes',(req,res)=>{const u=req.user,b=req.body;role(u,'teacher');const c={id:id(),teacherId:u.id,name:str(b.name,'Class name',120),subject:str(b.subject,'Subject',40),section:str(b.section,'Section',40),room:String(b.room||'').slice(0,80),description:String(b.description||'').slice(0,2000),color:/^#[0-9a-f]{6}$/i.test(b.color)?b.color:'#8b7cf8',limit:Math.floor(num(b.limit||40,1,500,'Student limit')),students:[],code:randomBytes(8).toString('hex').slice(0,7).toUpperCase(),createdAt:now(),archivedAt:null};state.classes.push(c);save();res.json(c);});
app.post('/api/classes/join',(req,res)=>{role(req.user,'student');const c=state.classes.find(c=>c.code===String(req.body.code).trim().toUpperCase()&&!c.archivedAt);if(!c)fail('No active class matches this code.');if(c.students.includes(req.user.id))fail('You have already joined this class.');if(c.students.length>=c.limit)fail('This class is full.');c.students.push(req.user.id);notify(c.teacherId,`${req.user.name} joined ${c.name}.`);save();res.json(c);});
app.post('/api/classes/:id/archive',(req,res)=>{const c=classroom(req.user,req.params.id,true,false);if(req.body.restore){if(!c.archivedAt)fail('Class is already active.');if(Date.now()-Date.parse(c.archivedAt)>48*3600000)fail('The 48-hour restore window has ended.');c.archivedAt=null;}else c.archivedAt=now();save();res.json({ok:true});});
app.post('/api/posts',(req,res)=>{const u=req.user,b=req.body;role(u,'teacher');const classes=b.broadcast?state.classes.filter(c=>c.teacherId===u.id&&!c.archivedAt):[classroom(u,b.classId,true)];const text=str(b.text,'Announcement');const fileId=attachment(u,b.fileId);for(const c of classes){state.posts.unshift({id:id(),classId:c.id,authorId:u.id,text,fileId,createdAt:now()});members(c,`New announcement in ${c.name}.`);}save();res.json({ok:true});});
app.post('/api/materials',(req,res)=>{const u=req.user,b=req.body;role(u,'teacher');const title=str(b.title,'Title',150),fileId=attachment(u,b.fileId);let url=null;if(b.url){try{url=new URL(b.url);if(!['https:','http:'].includes(url.protocol))throw Error();url=url.href;}catch{fail('Enter a valid http or https link.');}}if(!fileId&&!url)fail('Upload a file or provide a resource link.');const classes=b.broadcast?state.classes.filter(c=>c.teacherId===u.id&&!c.archivedAt):[classroom(u,b.classId,true)];for(const c of classes){state.materials.push({id:id(),classId:c.id,title,fileId,url,createdAt:now()});members(c,`New learning material: ${title}.`);}save();res.json({ok:true});});
app.post('/api/assignments',(req,res)=>{const b=req.body,c=classroom(req.user,b.classId,true);const a={id:id(),classId:c.id,title:str(b.title,'Title',150),description:str(b.description,'Instructions'),due:date(b.due),points:num(b.points,1,10000,'Points'),fileId:attachment(req.user,b.fileId),createdAt:now()};state.assignments.push(a);members(c,`New assignment: ${a.title}.`);save();res.json(a);});
app.post('/api/assignments/:id/submit',(req,res)=>{role(req.user,'student');const a=state.assignments.find(a=>a.id===req.params.id);if(!a)fail('Assignment not found.',404);const c=classroom(req.user,a.classId);if(state.submissions.some(s=>s.assignmentId===a.id&&s.studentId===req.user.id))fail('You have already submitted this assignment.');const fileId=attachment(req.user,req.body.fileId);const text=String(req.body.text||'').trim().slice(0,20000);if(!text&&!fileId)fail('Add your answer or a file.');state.submissions.push({id:id(),assignmentId:a.id,studentId:req.user.id,text,fileId,createdAt:now(),late:Date.now()>Date.parse(a.due),grade:null,feedback:''});notify(c.teacherId,`${req.user.name} submitted ${a.title}.`);save();res.json({ok:true});});
app.post('/api/submissions/:id/grade',(req,res)=>{const s=state.submissions.find(s=>s.id===req.params.id);if(!s)fail('Submission not found.',404);const a=state.assignments.find(a=>a.id===s.assignmentId);classroom(req.user,a.classId,true);s.grade=num(req.body.grade,0,a.points,'Grade');s.feedback=String(req.body.feedback||'').slice(0,5000);notify(s.studentId,`Your grade for ${a.title}: ${s.grade}/${a.points}.`);save();res.json({ok:true});});
app.post('/api/attendance/sessions',async(req,res)=>{const b=req.body,c=classroom(req.user,b.classId,true);const minutes=num(b.minutes,1,60,'Duration');const s={id:id(),classId:c.id,date:now().slice(0,10),token:randomBytes(32).toString('hex'),expires:Date.now()+minutes*60000,createdAt:now()};state.attendanceSessions.push(s);save();const url=`${process.env.BASE_URL||'http://localhost:3000'}/?attendance=${s.token}`;res.json({...s,url,qr:await QRCode.toDataURL(url)});});
app.post('/api/attendance/checkin',(req,res)=>{role(req.user,'student');const s=state.attendanceSessions.find(s=>s.token===req.body.token);if(!s||s.expires<Date.now())fail('Attendance code is invalid or expired.');classroom(req.user,s.classId);if(state.attendance.some(a=>a.classId===s.classId&&a.date===s.date&&a.studentId===req.user.id))fail('Attendance has already been recorded for today.');state.attendance.push({id:id(),classId:s.classId,date:s.date,studentId:req.user.id,status:'present',createdAt:now()});save();res.json({ok:true});});
app.post('/api/attendance/manual',(req,res)=>{const b=req.body,c=classroom(req.user,b.classId,true);if(!c.students.includes(b.studentId))fail('Student is not enrolled.');if(!['present','absent','late','excused'].includes(b.status))fail('Choose a valid status.');const d=date(b.date).slice(0,10);let a=state.attendance.find(a=>a.classId===c.id&&a.studentId===b.studentId&&a.date===d);if(a)a.status=b.status;else state.attendance.push({id:id(),classId:c.id,studentId:b.studentId,date:d,status:b.status,createdAt:now()});if(!state.attendanceSessions.some(s=>s.classId===c.id&&s.date===d))state.attendanceSessions.push({id:id(),classId:c.id,date:d,expires:0,createdAt:now()});save();res.json({ok:true});});
app.post('/api/quizzes',(req,res)=>{const b=req.body,c=classroom(req.user,b.classId,true);if(!Array.isArray(b.questions)||!b.questions.length||b.questions.length>50)fail('Add between 1 and 50 questions.');const questions=b.questions.map(q=>{if(!Array.isArray(q.options)||q.options.length<2||q.options.length>6)fail('Each question needs 2 to 6 options.');const answer=num(q.answer,0,q.options.length-1,'Correct option');if(!Number.isInteger(answer))fail('Invalid answer.');return {text:str(q.text,'Question',1000),options:q.options.map(o=>str(o,'Option',500)),answer};});const q={id:id(),classId:c.id,title:str(b.title,'Title',150),minutes:num(b.minutes,1,180,'Time limit'),status:'draft',questions,createdAt:now()};state.quizzes.push(q);save();res.json(q);});
app.post('/api/quizzes/:id/status',(req,res)=>{const q=state.quizzes.find(q=>q.id===req.params.id);if(!q)fail('Quiz not found.',404);classroom(req.user,q.classId,true);if(!['draft','live','closed'].includes(req.body.status))fail('Invalid status.');q.status=req.body.status;save();res.json({ok:true});});
app.post('/api/quizzes/:id/start',(req,res)=>{role(req.user,'student');const q=state.quizzes.find(q=>q.id===req.params.id);if(!q)fail('Quiz not found.',404);classroom(req.user,q.classId);if(q.status!=='live')fail('This quiz is not live.');let a=state.attempts.find(a=>a.quizId===q.id&&a.studentId===req.user.id);if(a?.submittedAt)fail('You have already completed this quiz.');if(!a){a={id:id(),quizId:q.id,studentId:req.user.id,startedAt:now(),deadline:Date.now()+q.minutes*60000};state.attempts.push(a);save();}res.json(a);});
app.post('/api/quizzes/:id/submit',(req,res)=>{role(req.user,'student');const q=state.quizzes.find(q=>q.id===req.params.id);if(!q)fail('Quiz not found.',404);classroom(req.user,q.classId);const a=state.attempts.find(a=>a.quizId===q.id&&a.studentId===req.user.id);if(!a||a.submittedAt)fail('No active attempt, or already submitted.');if(q.status!=='live')fail('This quiz is closed.');const expired=Date.now()>a.deadline+3000;const answers=Array.isArray(req.body.answers)?req.body.answers:[];a.score=expired?0:q.questions.filter((q,i)=>q.answer===answers[i]).length;a.total=q.questions.length;a.submittedAt=now();a.expired=expired;save();res.json(a);});
app.post('/api/polls',(req,res)=>{const b=req.body,c=classroom(req.user,b.classId,true);if(!Array.isArray(b.options)||b.options.length<2||b.options.length>6)fail('Add 2 to 6 poll options.');state.polls.push({id:id(),classId:c.id,title:str(b.title,'Question',200),options:b.options.map(o=>str(o,'Option',100)),votes:[],createdAt:now()});save();res.json({ok:true});});
app.post('/api/polls/:id/vote',(req,res)=>{role(req.user,'student');const p=state.polls.find(p=>p.id===req.params.id);if(!p)fail('Poll not found.',404);classroom(req.user,p.classId);if(p.votes.some(v=>v.userId===req.user.id))fail('You already voted.');const option=num(req.body.option,0,p.options.length-1,'Option');if(!Number.isInteger(option))fail('Invalid option.');p.votes.push({userId:req.user.id,option});save();res.json({ok:true});});
app.post('/api/links',(req,res)=>{role(req.user,'guardian');const student=state.users.find(u=>u.email===String(req.body.email).toLowerCase().trim()&&u.role==='student');if(!student)fail('No student account matches this email.');if(state.links.some(l=>l.guardianId===req.user.id&&l.studentId===student.id))fail('A link request already exists.');state.links.push({id:id(),guardianId:req.user.id,studentId:student.id,status:'pending'});notify(student.id,`${req.user.name} requested access to your progress. Review it in Guardian access.`);save();res.json({ok:true});});
app.post('/api/links/:id',(req,res)=>{const l=state.links.find(l=>l.id===req.params.id&&l.studentId===req.user.id);if(!l)fail('Request not found.',404);if(!['approved','rejected'].includes(req.body.status))fail('Invalid status.');l.status=req.body.status;notify(l.guardianId,`Your guardian access request was ${l.status}.`);save();res.json({ok:true});});
app.get('/api/reports/:studentId',(req,res)=>{if(!studentIds(req.user).includes(req.params.studentId))fail('Access denied.',403);const cids=state.classes.filter(c=>c.students.includes(req.params.studentId)&&(req.user.role!=='teacher'||c.teacherId===req.user.id)).map(c=>c.id);const m=metrics(req.params.studentId,cids);const csv=s=>'"'+String(s??'No data').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Student','Average grade (%)','Attendance (%)','Quiz average (%)','Submission rate (%)'],[m.name,m.average,m.attendance,m.quiz,m.submission],[],['Assignment','Grade','Maximum','Feedback']];state.submissions.filter(s=>s.studentId===m.studentId).forEach(s=>{const a=state.assignments.find(a=>a.id===s.assignmentId&&cids.includes(a.classId));if(a)rows.push([a.title,s.grade,a.points,s.feedback]);});res.attachment('smartclass-progress.csv').type('text/csv').send(rows.map(r=>r.map(csv).join(',')).join('\r\n'));});
app.post('/api/messages',(req,res)=>{const b=req.body;if(b.classId){if(req.user.role==='guardian')fail('Guardians cannot use class chat.',403);classroom(req.user,b.classId);}else{if(!state.users.some(u=>u.id===b.to))fail('Recipient not found.');const shared=state.classes.some(c=>[c.teacherId,...c.students].includes(req.user.id)&&[c.teacherId,...c.students].includes(b.to));const linked=state.links.some(l=>l.status==='approved'&&[l.guardianId,l.studentId].includes(req.user.id)&&[l.guardianId,l.studentId].includes(b.to));if(!shared&&!linked)fail('You can message your class members or approved linked account.',403);}state.messages.push({id:id(),from:req.user.id,to:b.classId?null:b.to,classId:b.classId||null,text:str(b.text,'Message',3000),createdAt:now()});if(b.to)notify(b.to,`New message from ${req.user.name}.`);save();res.json({ok:true});});
app.post('/api/events',(req,res)=>{const b=req.body,c=classroom(req.user,b.classId,true);let url;try{url=new URL(b.url);if(url.protocol!=='https:')throw Error();}catch{fail('Use an HTTPS meeting link.');}state.events.push({id:id(),classId:c.id,title:str(b.title,'Title',150),start:date(b.start),url:url.href,createdAt:now()});members(c,`New meeting scheduled: ${b.title}.`);save();res.json({ok:true});});
app.post('/api/notifications/read',(req,res)=>{state.notifications.filter(n=>n.userId===req.user.id).forEach(n=>n.read=true);save();res.json({ok:true});});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/\.(pdf|txt|png|jpg|jpeg|docx|pptx|xlsx|csv|zip)$/i.test(file.originalname))});
app.post('/api/upload',upload.single('file'),(req,res)=>{if(!req.file)fail('Supported files: PDF, text, images, Office documents, CSV and ZIP (up to 10 MB).');const f={id:id(),ownerId:req.user.id,name:path.basename(req.file.originalname),size:req.file.size};fs.writeFileSync(path.join(dataDir,f.id),req.file.buffer);state.files.push(f);save();res.json(f);});
app.get('/api/files/:id',(req,res)=>{const f=state.files.find(f=>f.id===req.params.id);if(!f)fail('File not found.',404);const ids=studentIds(req.user);const accessible=cid=>state.classes.some(c=>c.id===cid&&(c.teacherId===req.user.id||c.students.includes(req.user.id)||(req.user.role==='guardian'&&c.students.some(s=>ids.includes(s)))));const shared=[...state.posts,...state.materials,...state.assignments].some(x=>x.fileId===f.id&&accessible(x.classId));const submitted=state.submissions.some(s=>s.fileId===f.id&&(s.studentId===req.user.id||(req.user.role==='guardian'&&ids.includes(s.studentId))||state.assignments.some(a=>a.id===s.assignmentId&&state.classes.some(c=>c.id===a.classId&&c.teacherId===req.user.id))));if(f.ownerId!==req.user.id&&!shared&&!submitted)fail('Access denied.',403);res.download(path.join(dataDir,f.id),f.name);});
app.post('/api/offline/verify',(req,res)=>{role(req.user,'teacher');let token;try{token=JSON.parse(req.body.token);}catch{fail('Invalid offline token.');}const a=state.assignments.find(a=>a.id===token.assignmentId);if(!a)fail('Assignment not found.');const c=classroom(req.user,a.classId,true);if(!c.students.includes(token.studentId)||typeof token.nonce!=='string'||token.nonce.length<16)fail('Invalid token or student.');if(state.submissions.some(s=>s.assignmentId===a.id&&s.studentId===token.studentId))fail('This student already submitted.');state.submissions.push({id:id(),assignmentId:a.id,studentId:token.studentId,text:'Offline work verified in person by teacher.',createdAt:now(),late:Date.now()>Date.parse(a.due),grade:null,feedback:'',offline:true});state.offline.push({...token,status:'verified',verifiedAt:now()});notify(token.studentId,`Offline submission verified: ${a.title}.`);save();res.json({ok:true});});
app.post('/api/ai',async(req,res)=>{const message=str(req.body.message,'Message',2000);if(!process.env.OPENROUTER_API_KEY||!process.env.OPENROUTER_MODEL)return res.status(503).json({error:'AI is not connected yet. Add OPENROUTER_API_KEY and OPENROUTER_MODEL to .env, then restart the server.'});if(req.session.aiAt&&Date.now()-req.session.aiAt<3000)fail('Please wait a moment before sending another message.',429);req.session.aiAt=Date.now();const context={role:req.user.role,classes:state.classes.filter(c=>c.teacherId===req.user.id||c.students.includes(req.user.id)).map(c=>c.name)};const messages=[{role:'system',content:`You are SmartClass, a helpful academic tutor. Guide learning; do not claim to change records. User context: ${JSON.stringify(context)}`},...(req.session.history||[]).slice(-20),{role:'user',content:message}];const result=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENROUTER_MODEL,messages}),signal:AbortSignal.timeout(30000)});if(!result.ok)fail('The AI provider is unavailable. Please try again later.',502);const json=await result.json();const reply=json.choices?.[0]?.message?.content;if(!reply)fail('The AI provider returned an empty response.',502);req.session.history=[...messages.slice(1),{role:'assistant',content:reply}].slice(-20);save();res.json({reply});});
app.use('/api',(req,res)=>res.status(404).json({error:'Endpoint not found.'}));
app.get('/vendor/chart.js',(req,res)=>res.sendFile(path.join(__dirname,'node_modules/chart.js/dist/chart.umd.js')));
app.use(express.static(path.join(__dirname,'public')));
app.use((err,req,res,next)=>{if(err.code==='LIMIT_FILE_SIZE')return res.status(400).json({error:'File must be smaller than 10 MB.'});if(!err.status)console.error(err);res.status(err.status||500).json({error:err.status?err.message:'Something went wrong. Please try again.'});});
const port=Number(process.env.PORT)||3000;
if(require.main===module)app.listen(port,()=>console.log(`SmartClass running at http://localhost:${port}`));
module.exports={app,db};
