const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'smartclass-test-'));
const {app,db}=require('../server');
let server,base;
before(async()=>{server=app.listen(0);await new Promise(r=>server.once('listening',r));base='http://localhost:'+server.address().port;});
after(()=>{server.close();db.close();fs.rmSync(process.env.DATA_DIR,{recursive:true,force:true});});
async function request(route,body,cookie){const r=await fetch(base+'/api'+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:(r.headers.get('content-type')||'').includes('json')?await r.json():await r.text(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function login(role){const r=await request('/auth/login',{email:role+'@smartclass.local',password:'password123'});assert.equal(r.status,200);return r.cookie;}
test('authenticated role workflows, validation and privacy',async()=>{
 assert.equal((await request('/state')).status,401);
 const teacher=await login('teacher'),student=await login('student'),guardian=await login('guardian');
 assert.equal((await request('/classes',{name:'Forbidden'},student)).status,403);
 const register=await request('/auth/register',{name:'Other teacher',email:'other@example.com',password:'strongpass123',role:'teacher'});
 assert.equal(register.status,200);
 assert.equal((await request('/classes/c1/archive',{},register.cookie)).status,403);
 assert.equal((await request('/state',undefined,guardian)).data.analytics.length,0);
 assert.equal((await request('/reports/student',undefined,guardian)).status,403);
 assert.equal((await request('/links',{email:'student@smartclass.local'},guardian)).status,200);
 let data=(await request('/state',undefined,student)).data;
 const link=data.links[0];assert.equal(link.status,'pending');
 assert.equal((await request('/links/'+link.id,{status:'approved'},guardian)).status,404);
 await request('/links/'+link.id,{status:'approved'},student);
 assert.equal((await request('/reports/student',undefined,guardian)).status,200);
 const c=(await request('/classes',{name:'Testing class',subject:'T101',section:'1',limit:1},teacher)).data;
 assert.equal(c.code.length,7);
 assert.equal((await request('/classes/join',{code:c.code},student)).status,200);
 assert.equal((await request('/classes/join',{code:c.code},student)).status,400);
 const a=(await request('/assignments',{classId:c.id,title:'A test assignment',description:'Submit your work',due:new Date(Date.now()-1000).toISOString(),points:50},teacher)).data;
 assert.equal((await request('/assignments/'+a.id+'/submit',{text:'My completed work'},student)).status,200);
 assert.equal((await request('/assignments/'+a.id+'/submit',{text:'Duplicate'},student)).status,400);
 data=(await request('/state',undefined,teacher)).data;const submission=data.submissions.find(s=>s.assignmentId===a.id);assert.equal(submission.late,true);
 assert.equal((await request('/submissions/'+submission.id+'/grade',{grade:51},teacher)).status,400);
 assert.equal((await request('/submissions/'+submission.id+'/grade',{grade:45,feedback:'Great work'},teacher)).status,200);
 assert.equal((await request('/submissions/'+submission.id+'/grade',{grade:10},student)).status,403);
 const qr=(await request('/attendance/sessions',{classId:c.id,minutes:1},teacher)).data;
 assert.equal(qr.token.length,64);assert.ok(qr.qr.startsWith('data:image/png'));
 assert.equal(new URL(qr.url).origin,base);
 assert.equal((await request('/attendance/checkin',{token:'bad'},student)).status,400);
 assert.equal((await request('/attendance/checkin',{token:qr.token},student)).status,200);
 assert.equal((await request('/attendance/checkin',{token:qr.token},student)).status,400);
 const q=(await request('/quizzes',{classId:c.id,title:'Test quiz',minutes:5,questions:[{text:'2 + 2?',options:['3','4'],answer:1}]},teacher)).data;
 assert.equal((await request('/quizzes/'+q.id+'/start',{},student)).status,400);
 await request('/quizzes/'+q.id+'/status',{status:'live'},teacher);
 data=(await request('/state',undefined,student)).data;assert.equal(data.quizzes.find(x=>x.id===q.id).questions[0].answer,undefined);
 await request('/quizzes/'+q.id+'/start',{},student);
 const result=await request('/quizzes/'+q.id+'/submit',{answers:[1]},student);assert.equal(result.data.score,1);
 assert.equal((await request('/quizzes/'+q.id+'/submit',{answers:[1]},student)).status,400);
 assert.equal((await request('/messages',{classId:c.id,text:'Class conversation'},guardian)).status,403);
 await request('/classes/'+c.id+'/archive',{},teacher);
 assert.equal((await request('/posts',{classId:c.id,text:'Blocked archive write'},teacher)).status,400);
 await request('/classes/'+c.id+'/archive',{restore:true},teacher);
 assert.equal((await request('/posts',{classId:c.id,text:'Restored class'},teacher)).status,200);
 await request('/links/'+link.id,{status:'rejected'},student);
 assert.equal((await request('/reports/student',undefined,guardian)).status,403);
 await request('/logout',{},teacher);
 assert.equal((await request('/state',undefined,teacher)).status,401);
});

test('same-origin browser login, rejected origin, attachment authorization and logout',async()=>{
 const body={email:'student@smartclass.local',password:'password123'};
 const loginResponse=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify(body)});
 assert.equal(loginResponse.status,200);
 const cookie=loginResponse.headers.get('set-cookie').split(';')[0];
 const badOrigin=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://unrelated.example'},body:JSON.stringify(body)});
 assert.equal(badOrigin.status,403);
 const invalid=await request('/auth/login',{...body,password:'incorrect'});
 assert.equal(invalid.status,401);
 const form=new FormData();form.append('file',new Blob(['private test document']), 'notes.txt');
 const upload=await fetch(base+'/api/upload',{method:'POST',headers:{Cookie:cookie},body:form});
 assert.equal(upload.status,200);
 const file=await upload.json();
 const download=await fetch(base+'/api/files/'+file.id,{headers:{Cookie:cookie}});
 assert.equal(await download.text(),'private test document');
 const guardian=await login('guardian');
 assert.equal((await request('/files/'+file.id,undefined,guardian)).status,403);
 assert.equal((await request('/logout',{},cookie)).status,200);
 assert.equal((await request('/state',undefined,cookie)).status,401);
});
